---
title: "Jonathan Berrisch's CV"
author: Jonathan Berrisch
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results = "asis",
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")
source("build_network.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1JwjpZ2qwJoA-nu3QDlOlotss-lGz7yF41DjNJ_yQ4HQ/edit?usp=sharing",
  pdf_mode = params$pdf_mode
)
```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if (params$pdf_mode) {
  cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
build_network_logo(CV$entries_data)
```


```{r}
if (params$pdf_mode) {
  cat("View this CV online with links at _berrisch.biz/cv_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/BerriJ/cv/raw/master/berrisch_cv.pdf)")
}
```

Personal {#personal}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```

Development Tools {#devtools}
--------------------------------------------------------------------------------

```{r}
CV %>% print_tool_bars()
```

Main
================================================================================

Jonathan Berrisch {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro")
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section("education")
```

Software Projects {data-icon=laptop data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section("software")
```


Research Experience {data-icon=flask-vial}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section("research_positions")
```



Industry Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block("industy_experience_aside")
```
:::

```{r}
CV %<>% print_section("industry_positions")
```


Publications {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section("publications")
```

Conferences and Workshops  {data-icon=chalkboard-teacher, data-concise=true}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block("conferences_aside")
```
:::

```{r}
CV %<>% print_section("conferences_workshops")
```

Voluntary  {data-icon=hands-helping}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block("voluntary_aside")
```
:::

```{r}
CV %<>% print_section("voluntary")
```

Interests  {data-icon=cookie-bite}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block("interests_aside")
```
:::

```{r}
CV %<>% print_section("interests")
```

```{r}
# CV %<>% print_links()
```

::: aside

<br /><br /><br /><br /><br /><br /><br /><br />

Last updated on `r Sys.Date()`.

Source: [github.com/BerriJ/cv](https://github.com/BerriJ/cv).
:::
